# Generated by Django 2.1.7 on 2020-05-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200522_1149'),
        ('core', '0006_auto_20200525_1932'),
    ]

    operations = [
    ]
